name: Tests
on:
    push:
      branches:
        - main
        - dev
jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo Welcome to the Github Actions workshop !
  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: unit-tests
        run: make tests_run > output.txt
      - name: coverage
        run: make coverage > output.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_artifact
          path: output.txt
  function-tests_outputs:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: build
        run: make
      - name: unit-tests
        run: ./functional-test.sh > output.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_artifact
          path: output.txt